apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hetaira-web
  name: hetaira-web
spec:
  minReadySeconds: 300
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: hetaira-web
  template:
    metadata:
      labels:
        app: hetaira-web
    spec:
      containers:
      - image: gcr.io/hetaira-dev/hetaira-web:latest
        name: hetaira-web
        ports:
        - containerPort: 3000
        env:
        - name: FIREBASE
          valueFrom: 
            secretKeyRef:
              name: firebase
              key: credentials
---
apiVersion: v1             
kind: Service
metadata:
  name: hetaira-web-service
spec:
  type: NodePort
  selector:
    app: hetaira-web
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: hetaira-web-certificate
spec:
  domains:
    - kylymnyk.com     
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ingress-security-config
spec:
  sslPolicy: hetaira-gke-ssl-policy
  redirectToHttps:
    enabled: true
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hetaira-web-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: hetaira-web-address
    networking.gke.io/managed-certificates: hetaira-web-certificate
    networking.gke.io/v1beta1.FrontendConfig: ingress-security-config
spec:
  backend:
    serviceName: hetaira-web-service
    servicePort: 80             

