apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hetaira-web
  name: hetaira-web
spec:
  minReadySeconds: 300
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: hetaira-web
  template:
    metadata:
      labels:
        app: hetaira-web
    spec:
      containers:
      - image: gcr.io/hetaira-dev/hetaira-web:latest
        name: hetaira-web
        ports:
        - containerPort: 8080
        env:
        - name: FIREBASE
          valueFrom: 
            secretKeyRef:
              name: firebase
              key: credentials
---
apiVersion: v1             
kind: Service
metadata:
  name: hetaira-web-service
spec:
  selector:
    app: hetaira-web
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000